### PR TITLE
Feature/manage gau expenditures

### LINKED ISSUE #12: Manage GAU Expenditures
Create a Lightning Component to manage the GAU Expenditures.

### PR DESCRIPTION
**Pull request by thombehrens**
This PR adds a Lightning Web Component to add the "Manage Expenditures" functionality to a Disbursement Lightning Record Page (LRP).

It fulfills the functional equivalent of the first five user stories described [here](https://docs.google.com/document/d/1ZvwNnCqp4T6hijb5DF0xAJQoQlGq15JTaG3BtcBFQ3c/edit), the difference being that the component is hosted on an LRP instead of it's own Visualforce page accessed via list button. As such, the functionality of a "refresh list" button was also added to help w/ data loading.

This PR also moves the entire repository over to sfdx format. As such, almost every file is present in the diff. At no point was any xml edited or metadata pulled from the org, so looking at the true value add can be seen by looking in the classes/ and lwc/ folders. But, we may have some impact on Release Management. @Nickers3 and @davisagli please take note of this. 

Setup for QA:
1. Setup > Session Settings > uncheck the "Enable secure and persistent browser caching to improve performance" box, & save.
2. Create a Funding Program, Funding Request, and Disbursement. Navigate to the Disbursement's record page. Select "Edit Page" from the gear dropdown (next to Setup, Developer Console, etc.)
3. in the page editor, add the manageExpenditures custom component to the record page in a place of your choosing. Activate it for the relevant apps, record types, and profiles.
4. To have workable data, ensure that some GAUs have been created (and are active), and that the Disbursement has an amount that is nonzero.

Note for Junette: I have not been able to reliably reproduce the error we were seeing which caused some expenditures to get intermittently deleted. As such, I *believe* I have fixed the problem, but can't say for certain. 

Closes #12

### CODE REVIEW

**Comment by Nickers3** [comment]
@jlantz @davisagli I noticed the feature test for our newest pull request failed.  I tried updating the org json files to align with the recommended structure in the error, however get a new error based on API version.  Our cumulusci/yml and sfdx-project.json are both set to 47.  Are we needing to be on a different API version?

Here is the error below:

=== Component Failures [2]
TYPE   FILE                                         NAME                                   PROBLEM
─────  ───────────────────────────────────────────  ─────────────────────────────────────  ─────────────────────────────────────────────
Error  shape/settings/Chatter.settings              settings/Chatter.settings              Not available for deploy for this API version
Error  shape/settings/LightningExperience.settings  settings/LightningExperience.settings  Not available for deploy for this API version

ERROR running force:org:create:  Failed to deploy settings to scratch org.

**Comment by thombehrens** [comment]
@Nickers3 @jlantz @davisagli I'm realizing I've been a poor steward of the MetaCI feedback up until now - my apologies!

On the build for the most recent commit here, I am seeing the warning Nick mentions, but I'm also seeing some Apex failures. Everything is passing in the scratch org, but I'll investigate and see what's up from that end.

**Comment by Nickers3** [comment]
@thombehrens thanks for the update.  Looks like it still failed the test.  I think this has to deal with our our cumulusci.yml and sfdx-project.json files are setup.  Specificially the API version.

**Comment by Nickers3** [comment]
NPSP is on API version 46 from what I can tell.

**Comment by thombehrens** [comment]
@Nickers3 tests are passing! Quite a doozy of a bug. I was using a method that acts differently depending on if the test is called from CI or from the Dev Console.

**Comment by Nickers3** [comment]
@thombehrens, thanks for the quick changes!  Mind letting me know when all of the changes are done.  I can push to the org for @jtan-trac to test.

**Comment by thombehrens** [comment]
@Nickers3 and @jtan-trac, The following 7 issues are **ready for retest**:
- Typo in "Success!" toast message
- Should there be a label like "Total Amount Remaining" in front of the number at the bottom of the tab?
- Percentages are not automatically calculated, should they be?
- When testing scenario 2, the total amount remaining was calculated to be -$0 after creating all allocations, preventing successful save
- It's possible to delete an allocation from a paid Disbursement.
- It's possible to change allocations after a Disbursement has been changed to a status of "Cancelled". 
- If an allocation was made to a GAU, then the GAU is changed to inactive, going back to modify allocations results in an error that is not intuitive for the user. See scenario 10.

Here are some issues on which I need clarification:
- Once allocations are created, it is not possible to update percentage allocations (only dollar amounts can be changed). Is this expected? **Currently, each line item can only have one "editable" field - either amount or percent. when the amount & percent is zero, either can be edited, but once editing begins, the other is locked. This was a decision made to emulate the Manage Allocations NPSP page. I *believe* that starting w/ only amounts editable is the same there, too. Although resetting after save I think is only us. The simplest solution here would be to allow edit on either field at any time, and remove the "greying out" functionality for whichever field is the "calculated" field. Auto-calculations will still work the same. Is that ok? I'm open to other suggestions.**
- It's possible to reduce the amount of a paid Disbursement after allocations have been created. **I've updated the component to not allow editing expenditures for paid or cancelled disbursements, but it looks like this refers to updating the Disbursement itself. This looks outside the scope of the stories, but we could write a trigger handler to prevent reducing the amount after expenditures have been paid. Is that something we want to include in this release?**
- It's not possible to fully allocate a Disbursement by percentage if you have to split the Disbursement into thirds. See test scenario 3. **I'm unsure what fix to implement here. $7000 is a number that cannot be divided into 3rds at the level of cents... should the extra cent be hidden? I'd imagine that whoever was allocating the money would just want to assign the extra cent to an allocation by giving it 33.3334%. Numbers that can be divided into thirds at the level of cents (e.g. $6999.99) work as expected, I believe.** 

The following issues aren't actionable by me at this time - they're just things that are baked into using custom components in a record page. To my knowledge, they've been discussed on the demo calls and been acknowledged as known risks, but we may need to revisit with the group before release. These are the issues I'm going to talk with Beth from Salesforce about, and see if she has any insight on how we could resolve these. Otherwise, we'll need a solution that involves documentation, etc. I can always write "Instructions" to go at the bottom of the component.
- GAU Expenditures related list does not update after the user clicks "Save Updates", should it?
- When looking up a GAU, there is no option to "View all results" or add a new GAU. Is this expected?
- It's not always obvious to the user when they should click Refresh List, since they may not be aware of when another user is updating the same Disbursement. This results in potential loss of data. See scenarios 6 and 7.

**Comment by Nickers3** [comment]
Thanks for the updates @thombehrens!  I'll add my two cents to the items:



Once allocations are created, it is not possible to update percentage allocations (only dollar amounts can be changed). 
I'm in favor of modeling with how the NPSP Manage Allocations works.  It would be a nice to have so we could log as an issue for a future update.

It's possible to reduce the amount of a paid Disbursement after allocations have been created.
I'd like to avoid going down the trigger handler route as I'd like a handful of use cases before we get into trigger handlers.  For now, this could likely be solved via documentation.

It's not possible to fully allocate a Disbursement by percentage if you have to split the Disbursement into thirds.
With the Payment Scheduler, there was some code written in to round up the last entry in the case of 33%.  This logic may be different since the rows are created one by one vs how the Payment Scheduler does the math in the background to create the rows.  If we can't build this one in easily, I'm ok forgoing knowing someone could split these either by decimals or 33, 33, 34.

For things baked into Lightning, could the component banner have a help text to state refresh the page for see the entries?  Since the component could be in different places by instance, we can keep the text pretty generic.  @jtan-trac any thoughts on your end?

**Comment by jtan-trac** [comment]
@Nickers3 @thombehrens I agree that documentation can be leveraged for all of these remaining items.

I guess my only hesitation is around the updating by percentage after allocations have been created - we could actually improve the functionality here and deviate from the NPSP Manage Allocations functionality. I haven't been around for the group conversations, but if the .org team is waiting to see what we do, and it's not a huge effort to make this change, we have the option of improving the UI for both. I can't really see a downside - and I like Thom's proposal for a solution.

**Comment by Nickers3** [comment]
@jtan-trac @thombehrens if we do open up both fields, would we need to add additional work on the back end to make sure the math ties out?  IE if someone entered 2,000 for one line and 30% for another, would we need to have additional work to make sure the numbers addup?

Another idea would be a radio button to allow the user to select amount or percentage.  The goal I'm thinking is I'd like people to pick one or the other, and limit when someone would use both.

**Comment by thombehrens** [comment]
@Nickers3 @jtan-trac we should be fine. Entering a value in one field will always overwrite the value in the other, so entering “30%” as the percent would calculate the proper amount, and overwrite the “$2000” as needed. 

Radio buttons could also work :)

**Comment by Nickers3** [comment]
@thombehrens as long as there is an override I'm ok with the idea of having both fields open.  I'd say we do this for the update.  How much effort do you think is needed to make this happen?

**Comment by thombehrens** [comment]
@Nickers3 @jtan-trac we'll be ready for re-test by the beginning of tomorrow :)

**Comment by jtan-trac** [comment]
I won't be able to test until after work tomorrow - so you've got a bit more time @thombehrens :)

**Comment by thombehrens** [comment]
@Nickers3 @jtan-trac Ok! I've implemented what we discussed above, and we're ready for retest! Please let me know if I should change the language on the banner - right now it's "Click 'Refresh List' to start with the latest data.

**Comment by jtan-trac** [comment]
Wow, that was fast @thombehrens ! @Nickers3 are you able to spin up an org for me to test?

**Comment by Nickers3** [comment]
@thombehrens is the jimmyjohns of outbound funds :).  @jtan-trac, I'll get ya a new org for testing by tomorrow.

**Comment by Nickers3** [comment]
@jtan-trac, new org created for you.  User link should be in your email.

**Comment by jtan-trac** [comment]
Got it - thanks @Nickers3 !

**Comment by jtan-trac** [comment]
@Nickers3 has all the updated code been pushed successfully? I'm not seeing the expenditures tab on the Disbursement record page. FYI @thombehrens

**Comment by Nickers3** [comment]
@jtan-trac, my bad.  I had forgotten to update the lightning page to include the component.

**Comment by Nickers3** [comment]
Should be there now.

**Comment by jtan-trac** [comment]
@Nickers3 @thombehrens I've finished retesting all scenarios and here's a summary of my observations:

- If a disbursement is in a status of paid and there are no expenditures (or the amount of expenditures is less than the total amount of the disbursement), they shouldn't see a warning on the expenditures tab. Right now, the user is warned that they cannot make any updates. If they do try to create an expenditure at this point, they can actually save their changes, so the only change would be to remove the warning.
- If a disbursement is in a status of paid and the total amount of expenditures is equal to the total amount of disbursement, the user sees the warning on the expenditures tab, which is correct. However, if they try to delete or add rows, they can still do so.
- If a disbursement is in a status of cancelled, the user sees the warning on the expenditures tab, which is correct. However, if they try to delete or add rows, they can still do so.
- If the disbursement amount is reduced after expenditures have been allocated, and the user switches back to the expenditures tab, the related list looks like it's stuck in a state of processing. If the user refreshes their browser tab, the processing stops. 
- If a disbursement is allocated to a GAU, then the GAU is marked as inactive (see scenario 10), should the user be able to change the allocation? Note that if the user attempts to create a new allocation to an inactive GAU, they will not be able to select the GAU. 
- Should the GAU Expenditures related list be added to the Related tab of the GAU record page?

**Comment by thombehrens** [comment]
@Nickers3 @jtan-trac I have added two changes based on Junette's feedback:
- When the warning for Paid/Cancelled disbursements appears, the entire table (all buttons and inputs) are now disabled. not just the save button.
- The warning only appears for Cancelled disbursements and Paid disbursements with existing expenditures. Paid disbursements with no expenditures can still create them. However! This means that as soon as the user saves the newly created expenditures, the table locks and they can no longer be editing or deleted, since they're on a paid expenditure. Please confirm this is what we want :).

- I can't really do anything about the last 3 points Junette made, so Nick I'll let you weigh in.

**Comment by Nickers3** [comment]
Thanks @jtan-trac and @thombehrens!  I am pushing the changes to the scratch org as we speak.  I'll comment on the items I can:

_If the disbursement amount is reduced after expenditures have been allocated, and the user switches back to the expenditures tab, the related list looks like it's stuck in a state of processing. If the user refreshes their browser tab, the processing stops._

I replicated the issue.   I did move past the processing dots by refreshing the page.  This seems to be more of a deal with Lightning and some of the refresh items we've noted before.

_If a disbursement is allocated to a GAU, then the GAU is marked as inactive (see scenario 10), should the user be able to change the allocation? Note that if the user attempts to create a new allocation to an inactive GAU, they will not be able to select the GAU._

We could probably go multiple directions on this one.  The dream world is if a GAU Expenditure has been created, they can update the allocation.  They cannot however create a new GAU Expenditure to an inactive allocation.  The simplest might be they cannot create or update any GAU Expenditure.  I'll ask the quip group for feedback.

_Should the GAU Expenditures related list be added to the Related tab of the GAU record page?_

I've been thinking about where it sits on the page layout.  Since admins can move to where ever they want on the page layout, I think it's ok to put the GAU Expenditures Related List and Component on the same page.  Do you think having them separated will be a more common use case?  Would refresh change if they were on different tabs?

**Comment by jtan-trac** [comment]
@Nickers3 I agree that we can ask the quip group for feedback on what happens when a GAU is marked inactive.

The last point about whether GAU Expenditures related list should be added to the GAU record page - this was an observation I made because I noticed the GAU Allocations related list on the GAU record page, but since we've added the new junction, I was asking if we should add the new related list on the GAU record page (I wasn't commenting on the expenditures tab of the Disbursement record page).

Though, to your point about the expenditures tab on Disbursement - I agree that it's okay to have them both on the same tab. It may be more common to have them separated (having the related list in the same place as other related lists).

**Comment by Nickers3** [comment]
@jtan-trac I see where you are going now.  I dug into the GAU object and there is an outbound funds page layout with it on.  Just wasn't assigned in the app.

**Comment by thombehrens** [comment]
I remember Bill Corkill asking a question on this point during the last call, and I *believe* we cleared what had been demonstrated - that users can edit expenditures w/ inactive GAUs, and that it was ok that clearing that GAU would make it unretrievable.

**Comment by Nickers3** [comment]
@thombehrens @jtan-trac, works for me.  Let's run with it.  Since we don't have validation rules built in, someone can always go to the record itself and create/edit if needed.

**Comment by Nickers3** [comment]
Per post on quip: I don’t think we should. This would prevent accidental editing of the expenditure. If it truly needs to be edited I’d be in favor of adding documentation that tells the user that the GAU should be temporarily reactivated. Just thinking there is often a separation of duties between those that manage GAU and the expenditure and allowing this might mess with Accounting functions if you start allowing changes to the expenditure after a GAU is inactive.

**Comment by Nickers3** [comment]
Guessing it will be easier to code don't allow on create/edit @thombehrens

**Comment by jtan-trac** [comment]
@Nickers3 @thombehrens let me know when I should retest!

**Comment by jtan-trac** [comment]
@Nickers3 @thombehrens when I go to manage expenditures on a scheduled disbursement, it looks like I can't modify any of the rows. I can add a row, but can't delete a row. I've attached a screenshot.
rows_locked_on_tab

**Comment by thombehrens** [comment]
Darn! Sorry about that, @jtan-trac. Let me test this a little bit more and figure out what's up.

**Comment by thombehrens** [comment]
Sorry to send you through the rigamarole again, @Nickers3, but I've done some UI tests of my own in a qa_org and I believe I've fixed the problem Junette was running into. Can you create a new org for her?

**Comment by Nickers3** [comment]
@jtan-trac, should have a new login in your inbox.

**Comment by jtan-trac** [comment]
Thanks @Nickers3 - got it, will do some testing tonight.

**Comment by jtan-trac** [comment]
@Nickers3 @thombehrens Only one question remains! Here's the scenario (the last scenario) I tested:

1. Create funding request and disbursement
2. Manage expenditures such that disbursement is paid from 3 GAUs.
3. **In a separate browser tab, mark one of the GAUs as inactive.** (trying to mimic someone from accounting doing the modification instead of the current user)
4. In the expenditures tab, **without refreshing**, update the expenditure allocations, then save.

I expected the save to be unsuccessful (i.e. the allocation to the now-inactive GAU should not be modified). However, the save was successful. All allocations were updated, and after saving, the allocation for the inactive GAU became greyed out.

Note that if I performed all actions in the same browser tab, refreshing between each step, then after the GAU is marked inactive, the expenditures tab will show the allocation to the inactive GAU as greyed out so the user cannot make any modifications to that allocation.

Thoughts? Is this something we address in documentation?

**Comment by Nickers3** [comment]
@jtan-trac thanks for testing!  This seems to be more of a lightning issue than anything else.  @thombehrens any ideas for making this work outside of documentation?

**Comment by thombehrens** [comment]
@Nickers3 Nothing comes to mind.

**Comment by Nickers3** [comment]
Sounds good.  Addressing via documentation is the way we'll go.

**Pull request merged**
